### ISSUE TITLE
Integrate PyUAVCAN

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/Yukon#12]
From @Zarkopafilis :

> Pyuavcan should start to be exposed in quart. I’m sure that my stubbed out controllers / modules are not a 100% best fit for this, so it could use some refactoring / prototyping

Difficulty: Normal and Architect level

Very early stage PyUAVCAN docs (I am still working on these): https://pyuavcan.readthedocs.io/

**Comment by TSC21** [comment]
This is now done, but a continuous progress is required to bring more features. Being tracked in https://github.com/UAVCAN/Yukon/projects/5 and https://github.com/UAVCAN/Yukon/projects/1.
