### ISSUE TITLE
Real-time subscription

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/yukon#14]
Subscribe to a subject, transfer messages over REST to the frontend. Relevant PyUAVCAN docs:

- https://pyuavcan.readthedocs.io/en/latest/pages/architecture.html#presentation-layer
- [`pyuavcan.dsdl.to_builtin()`](https://pyuavcan.readthedocs.io/en/latest/.apidoc_generated/pyuavcan.dsdl.html#pyuavcan.dsdl.to_builtin) -- accepts a DSDL object, returns a native dict that can be fed to json.dumps or other standard serializers.

**Comment by bbworld1** [comment]
Is this issue still open? If so, I'd be interested in helping out.

This could probably be implemented fairly simply as a WebSockets connection between the backend and frontend. I haven't looked too much into the pyuavcan side of it, however.

**Comment by pavel-kirienko** [comment]
This is not relevant at the moment. Might I interest you in collaborating with me on an alternative backend implementation that is itself based on UAVCAN? It is pure Python, no JS or any web technologies at the moment (but they may become relevant later when we get to the front-end part, unless we settle on something like [Dear ImGUI](https://github.com/ocornut/imgui) for UI). I have taken some basic steps and done some groundwork but it's barely 10% done.

**Comment by bbworld1** [comment]
I'd absolutely be interested!

Is this alternative backend planned to be integrated into Yukon, a new UAVCAN inspection GUI, or something different?

**Comment by pavel-kirienko** [comment]
Let's discuss here: https://forum.uavcan.org/t/yukon-take-three/1139
