### ISSUE TITLE
Style the UI

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/yukon#16]
From @Zarkopafilis:

> UI is almost “designed”, but again, we could use some 3rd party to tell us what they think on that

Difficulty: easy

**Comment by Zarkopafilis** [comment]
[design megathread with images and stuff](https://forum.uavcan.org/t/yukon-design-megathread/390/8)

Here are some screenshots for documentation purposes: We need some people who are not affiliated with the design of yukon to review these:
(If you can't easily tell what's going wrong, design is bad and we need to re-do it)

![grv](https://user-images.githubusercontent.com/5436722/61437201-2b8cdc00-a945-11e9-97b6-ddab30401f5a.png)
![nodedetails](https://user-images.githubusercontent.com/5436722/61437202-2c257280-a945-11e9-997e-7b62c73600a0.png)
![nodes](https://user-images.githubusercontent.com/5436722/61437203-2c257280-a945-11e9-9dfa-649e771cce0b.png)
![priorities](https://user-images.githubusercontent.com/5436722/61437204-2c257280-a945-11e9-9bc0-f589eaf5763c.png)
![regedit](https://user-images.githubusercontent.com/5436722/61437205-2cbe0900-a945-11e9-9a63-33b3c62d2ac1.png)
