### ISSUE TITLE
[Frontend/UI | Task] Update all logos

### ISSUE THREAD

**Issue by TSC21** [UAVCAN/Yukon#54]
Yokun logo (https://docs.google.com/presentation/d/1NlDg_dLLQg3dhRAhLk7QOldvpFgBOfzB1UYi-scjxd0/edit#slide=id.g7feebca2db_0_2):
![image](https://user-images.githubusercontent.com/5048656/82735618-e7aff380-9d1a-11ea-880b-43b374bf8e05.png)

UAVCAN logo:

![image](https://user-images.githubusercontent.com/5048656/82735633-f72f3c80-9d1a-11ea-9c20-565cdc0c2f28.png)

**Comment by arrowcircle** [comment]
I suggest to use svg images instead of png's.
